### PR TITLE
Update Russian

### PR DESCRIPTION
**Pull request by bboa**
Hey Jason!
I create about new translation file. I test it on real phone with 320x480 resolution, all is ok. Mail me if any issue. Best!

### CODE REVIEW

**Comment by bboa** [comment]
Thanks!
Also, we have a little problem with "Select mode", "Yes", "No" etc strings, that placed in smali resources. Jason, can I ask to add it to strings.xml for complete translation?
Thanks for advance!

**Comment by skullone** [comment]
Absolutely.  2.2.7 won't be ready for a few more days.

**Comment by bboa** [comment]
Fine, I will watch your repo for updates. Thanks for perfect job.

**Comment by skullone** [comment]
Please e-mail me directly.  I have an updated strings.xml for you but I'm
not ready to push it to my git.

**Pull request merged**
